namespace: ibb
serviceAccountName: ibb-cns-haystack

deployment:
  rollPods: true

image:
  repository: us-central1-docker.pkg.dev/padi-staging/public/cns-haystack
  pullPolicy: Always
  tag: latest

ibbCnsHaystack:
  appPort: 3100


dapr:
  logLevel: debug

ibbAuthentication:
  contextSecret: ibb-authorization
  contextKey: id
  tokenSecret: ibb-authorization
  tokenKey: token
