traefik:
  api:
    dashboard: true

  additionalArguments:
  - "--log.level=DEBUG"

  ports:
    n4-platform:
      port: 5011
      expose: true
      exposedPort: 5011
      protocol: TCP
    n4-station:
      port: 4911
      expose: true
      exposedPort: 4911
      protocol: TCP