---
apiVersion: v1
kind: ConfigMap
metadata:
  name: injection-configs
  namespace: {{ .Values.namespace }}
  labels:
    com.ibbproject/app: ibb-injector
data:
  # Annotate your pod to inject configurations:
  #   `injector.tunnel.ibbproject.com/request: "sleep-sidecar"`
  sleep.conf: |
    name: sleep-sidecar
    containers:
    - name: ubuntu
      image: ubuntu
      command:
        - "/bin/bash"
        - "-c"
        - "while true; do echo 'Ubuntu Sidecar is running...'; sleep 30; done"
  piko.conf: |
    name: piko-sidecar
    containers:
    - name: piko
      image: {{ .Values.injection.container.image }}:{{ .Values.injection.container.tag }}
      imagePullPolicy: {{ .Values.injection.container.imagePullPolicy }}
      command: ["piko"]
      args:
        - "agent"
        - "http"
        - "$(ENDPOINT_ID)"
        - "$(ENDPOINT_ADDR)"
        - "--config.path"
        - "/etc/piko/agent.conf"
        - "--connect.token"
        - "TODO"
      env:
        - name: ENDPOINT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['endpointId']
        - name: ENDPOINT_ADDR 
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['endpointAddr']

