---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ibb-tunnel
  namespace: {{ .Values.injection.namespace }}
data:
  sidecars.yaml: |
    - name: piko-sidecar
      containers:
      - name: piko
        image: us-central1-docker.pkg.dev/padi-staging/public/ibb-tunnel:latest
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /etc/podinfo
            name: podinfo
          - mountPath: /etc/piko/mnt
            name: piko-token
      volumes:
        - name: piko-token
          secret:
            secretName: piko-token


# data:
#   sidecars.yaml: |
#     name: piko-sidecar
#     containers:
#     - name: piko
#       image: us-central1-docker.pkg.dev/padi-staging/public/ibb-tunnel:latest
#       imagePullPolicy: Always
#       volumeMounts:
#         - mountPath: /etc/podinfo
#           name: podinfo
#         - mountPath: /etc/piko/mnt
#           name: piko-token
#     volumes:
#       - name: piko-token
#         secret:
#           secretName: piko-token