apiVersion: v1
kind: Secret
metadata:
  name: ibb-injector
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  sidecar-injector.crt: {{ .Values.injector.sidecarInjectorCrt | b64enc }}
  sidecar-injector.key: {{ .Values.injector.sidecarInjectorKey | b64enc }}