---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibb-injector
  namespace: kube-system
imagePullSecrets:
  - name: ibb-injector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: kube-system
  name: ibb-injector
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibb-injector
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: ibb-injector
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: ibb-injector
  apiGroup: rbac.authorization.k8s.io
