# Default values for ibb-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/padi-staging/public/april-8080
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

cnsDapr:
  enabled: "True"
  appPort: 3000
  cnsContext: "CONTEXT"
  cnsToken: "TOKEN"
  cnsPubsub: "cns-pubsub"
  cnsBroker: "padi"
  image: "us-central1-docker.pkg.dev/padi-staging/public/cns-dapr"
  imageTag: "latest"
  dapr:
    logLevel: info
    port: 3500


ktunnel:
  enabled: false
  # The Padi ID or Context ID. This will be set via cns-kube if installed.
  id: "ID"
  # The name of the sidecar config from the ktunnel sidecar injector
  # configuration
  sidecarConfig: "ibb-ktunnel"
  # The name of the secret on the cluster which holds the information
  # on connecting to the upstream kubernetes cluster
  kubeconfigSecretName: "kubeconfig"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
