
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.orchestrator.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.orchestrator.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.orchestrator.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
