---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ktunnel-config
  namespace: {{ .Values.namespace }}
  labels:
    com.ibbproject/app: ibb-ktunnel-sidecar-injector
data:
  ibb-ktunnel.conf: |
    name: ibb-ktunnel
    containers:
    - name: ktunnel
      image: {{ .Values.container.image }}:{{ .Values.container.tag }}
      volumeMounts:
        - mountPath: /root/.kube/
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/podinfo
          name: podinfo

