apiversion: v1
metadata:
  name: ibb-ktunnel-sidecar-injector
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  sidecar-injector.crt: {{ .Values.sidecarInjectorCrt | b64enc }}
  sidecar-injector.key: {{ .Values.sidecarInjectorKey | b64enc }}