apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ibb-application.fullname" . }}
  labels:
    {{- include "ibb-application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ibb-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if .Values.tunnel.enabled }}
        injector.tunnel.ibbproject.com/request: {{ .Values.tunnel.sidecarConfig | quote }}
        injector.tunnel.ibbproject.com/tunnelId: "{{ .Values.tunnel.id }}"
        injector.tunnel.ibbproject.com/tunnelExposePort: "{{ .Values.service.port }}"
      {{- end }}
      {{- if .Values.deployment.rollPods }}
        rollme: {{ randAlphaNum 5 | quote }} 
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ibb-application.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # serviceAccountName: {{ include "ibb-application.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.env }}
          env:
          {{- range $key, $value := .Values.image.env }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.tunnel.enabled }}
      volumes:
        - name: token
          secret:
            secretName: {{ .Values.tunnel.jwtSecretName }}
            #mountPath: /etc/piko/mnt
        - name: podinfo
          downwardAPI:
            items:
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
