injection:
  namespace: default 
  container:
    image: "us-central1-docker.pkg.dev/padi-staging/public/ibb-tunnel"
    tag: "latest"
    imagePullPolicy: "Always"

kubernetes-sidecar-injector:
  selectors:
    injectPrefix: injector.tunnel.ibbproject.com
    injectName: request
