apiVersion: v1
kind: Service
metadata:
  name: ibb-ktunnel-sidecar-injector
  namespace: kube-system
  labels:
    com.ibbproject/app: ibb-ktunnel-sidecar-injector
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  - name: http-metrics
    port: 80
    targetPort: http-metrics
    protocol: TCP
  selector:
    com.ibbproject/app: "ibb-ktunnel-sidecar-injector"
