---
name: Release Charts

on:
  push:
    branches:
      - main
      
permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Environment
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          helm repo add traefik https://traefik.github.io/charts
          helm repo add sidecar-injector https://opensource.expediagroup.com/kubernetes-sidecar-injector
          helm repo add promcom https://prometheus-community.github.io/helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0 
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true" # Do not repackage charts if they already exist

