# Copyright (C) 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Default values for Edgex.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

padi:
  ktunnelSidecar:
    enabled: true
    id: "padiThingId"

imagePullSecrets: []
# supply a list of secret names (in the current namespace) of type docker-registry

expose:
  type:
    # Option value: ClusterIP/NodePort/LoadBalancer
    core:
      command: ClusterIP
      data:  ClusterIP
      metadata: ClusterIP
    support:
      notifications: ClusterIP
      scheduler: ClusterIP
    appservice:
      rules: ClusterIP
      mqttexport: ClusterIP
      httpexport: ClusterIP
      appsample: ClusterIP
      metricsinfluxdb: ClusterIP
      rfidllrpinventory: ClusterIP
      externalmqtttrigger: ClusterIP
    device:
      virtual: ClusterIP
      rest: ClusterIP
      usbcamera: ClusterIP
      onvifcamera: ClusterIP
      mqtt: ClusterIP
      modbus: ClusterIP
      bacnet: ClusterIP
      coap: ClusterIP
      snmp: ClusterIP
      rfidllrp: ClusterIP
      gpio: ClusterIP
    ui: NodePort
    system: ClusterIP
    consul: NodePort
    redis: ClusterIP
    ekuiper: ClusterIP
    modbussimulator: ClusterIP
    mqttbroker: ClusterIP
    natsserver: ClusterIP
    bootstrapper: ClusterIP
    vault: ClusterIP

# edgex defines a set of configuration properties for application-level concerns
edgex:

  # app defines a single point in naming/referring to an application. For each application, the value
  # define its label name, resource name or base of the resource name, and service name.
  app:
    core:
      common_config: edgex-core-common-config-bootstrapper
      command: edgex-core-command
      data: edgex-core-data
      metadata: edgex-core-metadata
    support:
      notifications: edgex-support-notifications
      scheduler: edgex-support-scheduler
    appservice:
      rules: edgex-app-rules-engine
      mqttexport: edgex-app-mqtt-export
      httpexport: edgex-app-http-export
      appsample: edgex-app-sample
      metricsinfluxdb: edgex-app-metrics-influxdb
      rfidllrpinventory: edgex-app-rfid-llrp-inventory
      externalmqtttrigger: edgex-app-external-mqtt-trigger
    device:
      virtual: edgex-device-virtual
      rest: edgex-device-rest
      onvifcamera: edgex-device-onvif-camera
      usbcamera: edgex-device-usb-camera
      mqtt: edgex-device-mqtt
      modbus: edgex-device-modbus
      bacnet: edgex-device-bacnet
      coap: edgex-device-coap
      snmp: edgex-device-snmp
      rfidllrp: edgex-device-rfid-llrp
      gpio: edgex-device-gpio
    ui: edgex-ui
    consul: edgex-core-consul
    redis: edgex-redis
    ekuiper: edgex-kuiper
    vault: edgex-vault
    bootstrapper: edgex-security-bootstrapper
    secretstoresetup: edgex-security-secretstore-setup
    modbussimulator: edgex-modbus-simulator
    mqttbroker: edgex-mqtt-broker
    natsserver: edgex-nats-server

  # image defines configuration properties for docker-image-level concerns
  image:
    core:
      common_config:
        repository: edgexfoundry/core-common-config-bootstrapper
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      command:
        repository: edgexfoundry/core-command
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      data:
        repository: edgexfoundry/core-data
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      metadata:
        repository: edgexfoundry/core-metadata
        tag: "3.0.0"
        pullPolicy: IfNotPresent
    support:
      notifications:
        repository: edgexfoundry/support-notifications
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      scheduler:
        repository: edgexfoundry/support-scheduler
        tag: "3.0.0"
        pullPolicy: IfNotPresent
    appservice:
      rules:
        repository: edgexfoundry/app-service-configurable
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      appsample:
        repository: edgexfoundry/app-service-configurable
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      metricsinfluxdb:
        repository: edgexfoundry/app-service-configurable
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      rfidllrpinventory:
        repository: edgexfoundry/app-rfid-llrp-inventory
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      mqttexport:
        repository: edgexfoundry/app-service-configurable
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      httpexport:
        repository: edgexfoundry/app-service-configurable
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      externalmqtttrigger:
        repository: edgexfoundry/app-service-configurable
        tag: "3.0.0"
        pullPolicy: IfNotPresent
    device:
      virtual:
        repository: edgexfoundry/device-virtual
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      rest:
        repository: edgexfoundry/device-rest
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      onvifcamera:
        repository: edgexfoundry/device-onvif-camera
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      usbcamera:
        repository: edgexfoundry/device-usb-camera
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      mqtt:
        repository: edgexfoundry/device-mqtt
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      modbus:
        repository: edgexfoundry/device-modbus
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      bacnet:
        repository: edgexfoundry/device-bacnet
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      coap:
        repository: edgexfoundry/device-coap
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      snmp:
        repository: edgexfoundry/device-snmp
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      rfidllrp:
        repository: edgexfoundry/device-rfid-llrp
        tag: "3.0.0"
        pullPolicy: IfNotPresent
      gpio:
        repository: edgexfoundry/device-gpio
        tag: "3.0.0"
        pullPolicy: IfNotPresent
    ui:
      repository: edgexfoundry/edgex-ui
      tag: "3.0.0"
      pullPolicy: IfNotPresent
    consul:
      repository: hashicorp/consul
      tag: "1.15.2"
      pullPolicy: IfNotPresent
    redis:
      repository: redis
      tag: "7.0.11-alpine"
      pullPolicy: IfNotPresent
    ekuiper:
      repository: lfedge/ekuiper
      tag: "1.9.2-alpine"
      pullPolicy: IfNotPresent
    vault:
      repository: hashicorp/vault
      tag: "1.13.2"
      pullPolicy: IfNotPresent
    bootstrapper:
      repository: edgexfoundry/security-bootstrapper
      tag: "3.0.0"
      pullPolicy: IfNotPresent
    proxysetup:
      repository: edgexfoundry/security-proxy-setup
      tag: "3.0.0"
      pullPolicy: IfNotPresent
    secretstoresetup:
      repository: edgexfoundry/security-secretstore-setup
      tag: "3.0.0"
      pullPolicy: IfNotPresent
    modbussimulator:
      repository: nexus3.edgexfoundry.org:10003/edgex-devops/edgex-modbus-simulator
      tag: "latest"
      pullPolicy: IfNotPresent
    mqttbroker:
      repository: eclipse-mosquitto
      tag: "2.0.15"
      pullPolicy: IfNotPresent
    natsserver:
      repository: nats
      tag: "2.9.16-alpine"
      pullPolicy: IfNotPresent

  # port defines configuration properties for container, target and host ports
  port:
    core:
      data: 59880
      metadata: 59881
      command: 59882
    support:
      notifications: 59860
      scheduler: 59861
    appservice:
      rules: 59701
      mqttexport: 59703
      httpexport: 59704
      appsample: 59700
      metricsinfluxdb: 59707
      rfidllrpinventory: 59711
      externalmqtttrigger: 59706
    device:
      virtual: 59900
      rest: 59986
      usbcamera: 59983
      onvifcamera: 59984
      bacnet: 59980
      coap: 59988
      mqtt: 59982
      modbus: 59901
      snmp: 59993
      rfidllrp: 59989
      gpio: 59994
    system: 58890
    ui: 4000
    consul: 8500
    redis: 6379
    ekuiper: 59720
    modbussimulator: 1502
    mqttbroker: 1883
    natsserver: 4222
    vault: 8200

  # ports used by security bootstrapping for stage gating edgex init
  bootstrap:
    port:
      start: 54321
      readytorun: 54329
      secretstoretokensready: 54322
      databaseready: 54323
      registryready: 54324
      kongdbready: 54325

  # Duplicate default IP binding choice of docker-compose
  hostPortInternalBind: 127.0.0.1
  hostPortExternalBind: 0.0.0.0

  # replicas defines the number of replicas in a Deployment for the respective application
  replicas:
    core:
      common_config: 1
      command: 1
      data: 1
      metadata: 1
    support:
      notifications: 1
      scheduler: 1
    appservice:
      rules: 1
      mqttexport: 0
      httpexport: 0
      appsample: 0
      metricsinfluxdb: 0
      rfidllrpinventory: 0
      externalmqtttrigger: 0
    device:
      virtual: 1
      rest: 1
      usbcamera: 0
      onvifcamera: 0
      mqtt: 0
      modbus: 0
      bacnet: 0
      coap: 0
      snmp: 0
      rfidllrp: 0
      gpio: 0
    ui: 1
    system: 1
    consul: 1
    redis: 1
    ekuiper: 1
    modbussimulator: 0
    mqttbroker: 0
    natsserver: 0

  # UID/GID for container user
  security:
    enabled: false
    runAsUser: 2002
    runAsGroup: 2001
    tlsHost: edgex
    addConsulRoles: "app-external-mqtt-trigger,app-http-export,app-metrics-influxdb,app-mqtt-export,app-rfid-llrp-inventory,app-sample,device-bacnet-ip,device-coap,device-gpio,device-modbus,device-mqtt,device-onvif-camera,device-rfid-llrp,device-snmp,device-usb-camera"
    addServiceTokens: "app-external-mqtt-trigger,app-http-export,app-metrics-influxdb,app-mqtt-export,app-rfid-llrp-inventory,app-sample,device-bacnet-ip,device-coap,device-gpio,device-modbus,device-mqtt,device-onvif-camera,device-rest,device-rfid-llrp,device-snmp,device-usb-camera,device-virtual"
    addKnownSecrets: "redisdb[app-external-mqtt-trigger;app-http-export;app-metrics-influxdb;app-mqtt-export;app-rfid-llrp-inventory;app-sample;device-bacnet-ip;device-coap;device-gpio;device-modbus;device-mqtt;device-onvif-camera;device-rest;device-rfid-llrp;device-snmp;device-usb-camera;device-virtual],message-bus[app-external-mqtt-trigger;app-http-export;app-metrics-influxdb;app-mqtt-export;app-rfid-llrp-inventory;app-sample;device-bacnet-ip;device-coap;device-gpio;device-modbus;device-mqtt;device-onvif-camera;device-rest;device-rfid-llrp;device-snmp;device-usb-camera;device-virtual]"

  # resources defines the cpu and memory limits and requests for the respective application
  resources:
    core:
      common_config:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      command:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      data:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      metadata:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
    support:
      notifications:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      scheduler:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
    appservice:
      rules:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      mqttexport:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      httpexport:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      appsample:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      metricsinfluxdb:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      rfidllrpinventory:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      externalmqtttrigger:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
    device:
      virtual:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      rest:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      usbcamera:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      onvifcamera:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      mqtt:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      modbus:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      bacnet:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      coap:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      snmp:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      rfidllrp:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      gpio:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
    ui:
      enforceLimits: false
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 0.5
        memory: 256Mi
    system:
      enforceLimits: false
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 0.5
        memory: 256Mi
    consul:
      enforceLimits: false
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 0.5
        memory: 256Mi
    redis:
      enforceLimits: false
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 0.5
        memory: 256Mi
    ekuiper:
      enforceLimits: false
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 0.5
        memory: 256Mi
    vault:
      enforceLimits: false
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 0.5
        memory: 256Mi
    bootstrapper:
      enforceLimits: false
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 0.5
        memory: 256Mi
    secretstoresetup:
      enforceLimits: false
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 0.5
        memory: 256Mi
    modbussimulator:
      enforceLimits: false
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 0.5
        memory: 256Mi
    mqttbroker:
      enforceLimits: false
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 0.5
        memory: 256Mi
    natsserver:
      enforceLimits: false
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 0.5
        memory: 256Mi
  storage:
    useHostPath: true

    # nonSharedVolumesClassName used for services that does not share a storage volume with other services.
    nonSharedVolumesClassName: "rook-ceph-block"
    nonSharedVolumesAccessMode: "ReadWriteOnce"

    # sharedVolumesClassName used for services that share a storage volume
    sharedVolumesClassName: "rook-cephfs"
    # If this value is set to "ReadWriteOnce" it will trigger pod affinity rules.
    sharedVolumesAccessMode: "ReadWriteMany"

  features:
    # Available messagebus options: redis|mqtt|nats
    messagebusbackend: redis
    # MQTT broker address
    mqttBrokerAddress: ""
    # Writable pipeline functions HTTP export parameter URL
    httpExportURL: ""
    enableHostPort: false
